// @generated templates from cat2151/easychord2mml (main branch)
// Upstream: https://github.com/cat2151/easychord2mml
// Upstream-File: chordTemplates.js
// Upstream-SHA: 3cc7c8673e21e0a1412ac2271386a3d47aa872cd
// DO NOT EDIT this file manually. Re-copy chordTemplates.js from upstream main and add `export const chordTemplates: [string, string][] = ` to update.

export const chordTemplates: [string, string][] = [
  ["テンプレートを選んでください",
  ``],

  ["ドミソシの和音",
  `CM7`],

  [" II の和音",
  `IIm`],

  ["転回形",
  `IV IV^1 IV^2`],

  ["臨時オクターブ",
  `Key=D I IV^2, V^1, I`],

  ["bass is root",
  `Key=E, bass is root.
          I IV V`],

  ["drop2 / drop4 / drop2and4",
    `Key=Ab, Octave down, BPM100. |
      E.Piano2 drop2 IM7 IVM7 V6 |
      Str.2 drop4 IM7 IVM7 V6 |
      Choir drop2and4 IM7 IVM7 V6`],

  ["chord on bass note",
  `Key=F,
  I^1'/I IIIm'/I
  VIm^1/I IIm'/I
  V7^2/I`],

  ["Upper Structure",
  `US bIII/I7(o1)(o5) bVm^2/I7(o1)(o5)`],

  ["四度堆積",
    `Key=D bass is root. Strings1 | I4.2 I4.3 | I4.4 I4.5 I4.6 |`],

  ["Strings1",
  `Str.1 Key=F IM7,`],

  ["Strings2",
  `Str.2 Key=F IM7`],

  ["Choir",
  `Choir Key=D IM7`],

  ["Octave down",
  `Octave down bVI bVII`],

  ["BPM",
  `BPM180 Im bVI, bVII, I`],

  ["小節線",
  `Bass is root. Str.1 BPM130
  I | bIII | IV | bVI bVII`],

  ["タイムシフト機能 /*!!*/ を書いた場所から演奏します",
    `Bass is root. Str.1 BPM130
    I | bIII | IV | /*!!*/ bVI bVII`],

  ["コメント機能",
    `Bass is root. Key=C
    I^1'/ /*/* % 改行が必要なコメント
    */*/
    V7^2/, | /*/* [r: 改行なしのコメント(remark) ] */*/ I^1'/ |`],
];
