// @generated templates from cat2151/tonejs-mml-to-json (main branch)
// Upstream: https://github.com/cat2151/tonejs-mml-to-json
// Upstream-File: src/demos.ts
// Upstream-SHA: dfeeeda24a3f19d568c569e425589a1668f3c945
// DO NOT EDIT this file manually. Run: python .github/scripts/sync_vendor_tonejs_templates.py src/tonejsTemplates.ts

export const tonejsTemplates: [string, string][] = [
  ["Traditional Demo", "o4 l16 efg+abag+f e8.<e8.>e8"],
  ["Multi-track Demo", "o4 l8 cdefgab; o5 l16 ccccddddeeee; o3 l4 c e g"],
  ["@MembraneSynth", "@MembraneSynth o2 l4 c c c c e e e e g g g g"],
  ["@MetalSynth", "@MetalSynth o4 l8 c c c c e e e e g g g g"],
  ["@DuoSynth", "@DuoSynth o4 l8 cdefgab<c"],
  ["@FMSynth with Args", `@FMSynth{
  "harmonicity": 3,
  "modulationIndex": 10
} o4 l8 cdefgab<c`],
  ["@AMSynth with Args", `@AMSynth{
  "harmonicity": 2.5
} o4 l8 cdefgab<c`],
  ["@MonoSynth with Args", `@MonoSynth{
  "filter": {
    "Q": 2,
    "type": "lowpass",
    "rolloff": -12
  },
  "envelope": {
    "attack": 0.005
  }
} o3 l8 c c c c d d d d`],
  ["@PluckSynth with Args", `@PluckSynth{
  "attackNoise": 0.5,
  "dampening": 4000,
  "resonance": 0.95
} o4 l8 cdefgab<c`],
  ["@Synth with Args", `@Synth{
  "oscillator": {
    "type": "triangle"
  },
  "envelope": {
    "attack": 0.1,
    "decay": 0.2,
    "sustain": 0.5,
    "release": 1
  }
} o4 l4 c e g c`],
  ["Instrument Switching with Args", `@FMSynth{
  "harmonicity": 3
} o4 cde @AMSynth{
  "harmonicity": 2
} fga`],
  ["@Sampler (Piano)", `@Sampler{
  "urls": {
    "C4": "https://tonejs.github.io/audio/salamander/C4.mp3",
    "D#4": "https://tonejs.github.io/audio/salamander/Ds4.mp3",
    "F#4": "https://tonejs.github.io/audio/salamander/Fs4.mp3",
    "A4": "https://tonejs.github.io/audio/salamander/A4.mp3"
  },
  "release": 1
} o4 l8 cdefgab<c`],
  ["Chords (Basic)", "o4 l4 'ceg' 'dfb' 'ace' 'gbdf'"],
  ["Chords with @Sampler", `@Sampler{
  "urls": {
    "C4": "https://tonejs.github.io/audio/salamander/C4.mp3",
    "D#4": "https://tonejs.github.io/audio/salamander/Ds4.mp3",
    "F#4": "https://tonejs.github.io/audio/salamander/Fs4.mp3",
    "A4": "https://tonejs.github.io/audio/salamander/A4.mp3"
  },
  "release": 1
} o4 l4 'ceg' 'dfb' 'ace' 'gbdf'`],
  ["Chords with Accidentals", "o4 l4 'c+eg' 'df+a' 'eg+b' 'c-eg-'"],
  ["Chords with Duration", "o4 'c4eg' 'd8fb' 'e4ac'. 'f8gbd'.."],
  ["Mixed Single Notes and Chords", "o4 l8 c 'eg' d 'fac' e 'gb' c4"],
  ["@PingPongDelay with Args", `@PingPongDelay{
  "delayTime": "8n"
} o4 l8 cdefgab<c`],
  ["@PingPongDelay (Multiple)", "@PingPongDelay @PingPongDelay o4 l8 cdefgab<c"],
  ["@PingPongDelay with Instrument", "@FMSynth @PingPongDelay o4 l8 cdefgab<c"],
  ["@DelayVibrato (Single)", "@DelayVibrato o4 l1 cdefgab<c"],
  ["@DelayVibrato with Instrument", "@FMSynth @DelayVibrato o4 l1 cdefgab<c"],
  ["@Reverb with Args", `@Reverb{
  "decay": 2.5
} o4 l8 cdefgab<c`],
  ["@FeedbackDelay with Args", `@FeedbackDelay{
  "delayTime": "8n",
  "feedback": 0.6
} o4 l8 cdefgab<c`],
  ["@Chorus with Args", `@Chorus{
  "frequency": 4,
  "delayTime": 2.5,
  "depth": 0.7
} o4 l8 cdefgab<c`],
  ["@Phaser with Args", `@Phaser{
  "frequency": 0.5,
  "octaves": 3,
  "baseFrequency": 350
} o4 l8 cdefgab<c`],
  ["@Tremolo with Args", `@Tremolo{
  "frequency": 10,
  "depth": 0.5
} o4 l8 cdefgab<c`],
  ["@Vibrato with Args", `@Vibrato{
  "frequency": 5,
  "depth": 0.1
} o4 l8 cdefgab<c`],
  ["Flanger Effect (Chorus)", `@Synth{
  "oscillator": {
    "type": "sawtooth"
  }
} @Chorus{
  "frequency": 0.2,
  "delayTime": 3,
  "depth": 0.9
} o4 l1 'cegb' 'cegb' 'cegb' 'cegb'`],
  ["@Distortion with Args", `@Distortion{
  "distortion": 0.8
} o4 l8 cdefgab<c`],
  ["@AutoFilter with Args", `@AutoFilter{
  "frequency": 1,
  "baseFrequency": 200,
  "octaves": 2.6
} o4 l8 cdefgab<c`],
  ["@AutoPanner with Args", `@AutoPanner{
  "frequency": 1
} o4 l8 cdefgab<c`],
  ["@AutoWah with Args", `@AutoWah{
  "baseFrequency": 100,
  "octaves": 6,
  "sensitivity": 0
} o4 l8 cdefgab<c`],
  ["@BitCrusher with Args", `@BitCrusher{
  "bits": 4
} o4 l8 cdefgab<c`],
  ["@Chebyshev with Args", `@Chebyshev{
  "order": 50
} o4 l8 cdefgab<c`],
  ["@Freeverb with Args", `@Freeverb{
  "roomSize": 0.7,
  "dampening": 3000
} o4 l8 cdefgab<c`],
  ["@FrequencyShifter with Args", `@FrequencyShifter{
  "frequency": 42
} o4 l8 cdefgab<c`],
  ["@JCReverb with Args", `@JCReverb{
  "roomSize": 0.5
} o4 l8 cdefgab<c`],
  ["@PitchShift with Args", `@PitchShift{
  "pitch": 7
} o4 l8 cdefgab<c`],
  ["@StereoWidener with Args", `@StereoWidener{
  "width": 0.7
} o4 l8 cdefgab<c`],
  ["Mixed Effects Chain with Args", `@Reverb{
  "decay": 2
} @Chorus{
  "frequency": 4
} @PingPongDelay{
  "delayTime": "8n"
} o4 l8 cdefgab<c`],
  ["Effects with Custom Instrument", "@FMSynth @Reverb @Chorus o4 l8 cdefgab<c"],
  ["Creative Effects Chain", `@Distortion{
  "distortion": 0.4
} @Chorus @Reverb{
  "decay": 1.5
} @FeedbackDelay{
  "delayTime": "8n"
} o4 l8 cdefgab<c`],
  ["Accidentals (Sharps & Flats)", "o4 l16 c c+ d d+ e f f+ g g+ a a+ b <c"],
  ["Rest and Rhythm", "o4 l8 c r e r g r e r c4 r4"],
  ["Dotted Notes", "o4 c4. d8 e4. f8 g4.. a16 b4"],
  ["Octave Control (< and >)", "o4 l8 cdefgab < cdefgab < c > bagfedc > bagfedc"],
  ["Comprehensive Demo", "@FMSynth o4 l8 c4. 'eg' d+ 'f+ac'. e r < c; @MonoSynth o3 l4 c e g c"],
];
